# Generated by Django 6.0.1 on 2026-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donativodonador',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Estadounidenses'), ('EUR', 'Euros')], default='MXN', max_length=3),
        ),
    ]
