# Generated by Django 6.0.1 on 2026-05-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0010_documentospersonales'),
        ('donadores', '0002_donativodonador_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('localidades', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'catalogo_cp',
            },
        ),
        migrations.RemoveField(
            model_name='donador',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='donador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='donador',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donador',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donador',
            name='domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='beneficiarios.direccion'),
        ),
        migrations.AddField(
            model_name='donador',
            name='tipo_donador',
            field=models.CharField(choices=[('CEI', 'CEI'), ('CANFRO', 'CANFRO'), ('OYE', 'OYE'), ('PARTICULAR', 'PARTICULAR'), ('EMPRESA', 'EMPRESA'), ('INSTITUCION', 'INSTITUCIÓN')], default='CEI', max_length=20),
        ),
        migrations.AlterField(
            model_name='donador',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
