# Generated by Django 6.0.1 on 2026-05-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donadores', '0003_catalogocp_remove_donador_apellido_m_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoCP',
        ),
    ]
