# Generated by Django 6.0.1 on 2026-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_remove_familia_area_laboral_escuela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='edad',
        ),
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
