# Generated by Django 6.0.1 on 2026-06-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0003_remove_familia_edad_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_estudiosocioeconomico', models.ForeignKey(db_column='id_estudiosocioeconomico', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='estudios.estudiosocioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'db_table': 'gasto',
            },
        ),
    ]
