# Generated by Django 6.0.1 on 2026-06-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0019_alter_beneficiario_estatus_and_more'),
        ('estudios', '0004_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiosocioeconomico',
            name='link_documento',
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='id_documento',
            field=models.ForeignKey(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_vinculados', to='beneficiarios.documentospersonales'),
        ),
    ]
