# Generated by Django 6.0.1 on 2026-06-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0005_remove_estudiosocioeconomico_link_documento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analisis',
        ),
    ]
