# Generated by Django 6.0.1 on 2026-05-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0004_remove_beneficiario_estatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id_escolaridad', models.AutoField(primary_key=True, serialize=False)),
                ('grado_escolar', models.CharField(max_length=50)),
                ('nivel_escolar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Escolaridad',
                'db_table': 'escolaridad',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('clave_escolar', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='DatosEscolares',
            fields=[
                ('id_datos_escolares', models.AutoField(db_column='id_escuela', primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_escolar', models.TextField(blank=True, null=True)),
                ('modalidad_educativa', models.CharField(blank=True, max_length=100, null=True)),
                ('id_seguimiento', models.OneToOneField(db_column='id_seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='datos_escolares', to='beneficiarios.seguimientobeneficiario')),
                ('id_escolaridad', models.ForeignKey(db_column='id_escolaridad', on_delete=django.db.models.deletion.PROTECT, to='escolaridad.escolaridad')),
                ('id_institucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.PROTECT, to='escolaridad.institucion')),
            ],
            options={
                'verbose_name_plural': 'Datos Escolares',
                'db_table': 'datos_escolares',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_boleta', models.CharField(max_length=50)),
                ('periodo_boleta', models.CharField(max_length=50)),
                ('promedio_boleta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('id_datos_escolares', models.ForeignKey(db_column='id_datos_escolares', on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='escolaridad.datosescolares')),
            ],
            options={
                'verbose_name_plural': 'Boletas',
                'db_table': 'boleta',
            },
        ),
    ]
