# Generated by Django 6.0.1 on 2026-05-11 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolaridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='clave_escolar',
        ),
        migrations.AddField(
            model_name='institucion',
            name='municipio_escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolaridad.municipioescuela'),
        ),
    ]
