# Generated by Django 6.0.1 on 2026-05-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolaridad', '0002_municipioescuela_remove_institucion_clave_escolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioescuela',
            name='nombre',
            field=models.CharField(max_length=170, unique=True),
        ),
    ]
