# Generated by Django 6.0.1 on 2026-06-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0006_delete_analisis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=50)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='estudios.estudiosocioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Análisis IA',
                'db_table': 'analisis',
            },
        ),
    ]
