# Generated by Django 6.0.1 on 2026-05-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_alter_expediente_apellido_m'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoBeneficiario',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nota_seguimiento', models.TextField()),
                ('id_beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='beneficiarios.beneficiario')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_periodo', to='periodos.periodo')),
            ],
            options={
                'verbose_name_plural': 'Seguimientos de Beneficiarios',
                'db_table': 'seguimiento_beneficiario',
            },
        ),
    ]
