# Generated by Django 6.0.1 on 2026-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_seguimientobeneficiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='estatus',
        ),
        migrations.AddField(
            model_name='seguimientobeneficiario',
            name='estatus',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
