# Generated by Django 6.0.1 on 2026-05-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_remove_beneficiario_estatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoEconomico',
            fields=[
                ('id_apoyo', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_entrega', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(default='Entregado', max_length=50)),
                ('id_seguimiento', models.ForeignKey(db_column='id_seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='apoyos_economicos', to='beneficiarios.seguimientobeneficiario')),
            ],
            options={
                'verbose_name_plural': 'Apoyos Económicos',
                'db_table': 'apoyo_economico',
            },
        ),
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id_servicio_social', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_seguimiento', models.ForeignKey(db_column='id_seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='beneficiarios.seguimientobeneficiario')),
            ],
            options={
                'verbose_name_plural': 'Obligaciones',
                'db_table': 'obligacion',
            },
        ),
        migrations.CreateModel(
            name='UsoServicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField()),
                ('asistencia', models.CharField(max_length=20)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('id_seguimiento', models.ForeignKey(db_column='id_seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='usos_servicios', to='beneficiarios.seguimientobeneficiario')),
            ],
            options={
                'verbose_name_plural': 'Uso de Servicios',
                'db_table': 'uso_servicios',
            },
        ),
    ]
