# Generated by Django 6.0.1 on 2026-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0005_apoyoeconomico_obligacion_usoservicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoservicios',
            name='numero_acompanantes',
            field=models.IntegerField(default=0, help_text='Cantidad de familiares o personas que entraron al servicio con el niño'),
        ),
    ]
