# Generated by Django 6.0.1 on 2026-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0006_usoservicios_numero_acompanantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoservicios',
            name='es_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usoservicios',
            name='numero_acompanantes',
            field=models.IntegerField(blank=True, default=0, help_text='Cantidad de familiares o personas que entraron al servicio con el niño', null=True),
        ),
    ]
