# Generated by Django 6.0.1 on 2026-05-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0007_usoservicios_es_familiar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usoservicios',
            name='es_familiar',
        ),
        migrations.AlterField(
            model_name='usoservicios',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usoservicios',
            name='numero_acompanantes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
