# Generated by Django 6.0.1 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0008_remove_usoservicios_es_familiar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografias',
            name='link',
        ),
        migrations.AddField(
            model_name='fotografias',
            name='foto_archivo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='evidencias_fotos/%Y/%m/'),
        ),
    ]
