# Generated by Django 6.0.1 on 2026-05-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0009_remove_fotografias_link_fotografias_foto_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosPersonales',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='documentos_personales/%Y/%m/')),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_personales', to='beneficiarios.expediente')),
            ],
            options={
                'db_table': 'documentos_personales',
            },
        ),
    ]
