# Generated by Django 6.0.1 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0010_documentospersonales'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
