# Generated by Django 6.0.1 on 2026-05-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0011_direccion_localidad_direccion_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geografia',
            fields=[
                ('id_geografia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=150)),
                ('colonia', models.CharField(max_length=150)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Geografías',
                'db_table': 'geografia',
            },
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='municipio',
        ),
        migrations.AddField(
            model_name='expediente',
            name='foto_principal',
            field=models.ForeignKey(blank=True, db_column='foto_principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_portada', to='beneficiarios.fotografias'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_geografia',
            field=models.ForeignKey(blank=True, db_column='id_geografia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='beneficiarios.geografia'),
        ),
    ]
