# Generated by Django 6.0.1 on 2026-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0012_geografia_remove_direccion_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default='2026-06-02'),
            preserve_default=False,
        ),
    ]
