# Generated by Django 6.0.1 on 2026-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0013_postulante_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(default='Activo', max_length=50),
        ),
    ]
