# Generated by Django 6.0.1 on 2026-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0014_beneficiario_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='pais',
        ),
        migrations.AddField(
            model_name='geografia',
            name='pais',
            field=models.CharField(blank=True, default='MX', max_length=100, null=True),
        ),
    ]
