# Generated by Django 6.0.1 on 2026-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0015_remove_direccion_pais_geografia_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
