# Generated by Django 6.0.1 on 2026-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0016_direccion_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geografia',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='geografia',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
