# Generated by Django 6.0.1 on 2026-06-07 04:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0017_alter_geografia_colonia_alter_geografia_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoeconomico',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='apoyoeconomico',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Graduado', 'Graduado'), ('Baja', 'Baja')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentospersonales',
            name='tipo_documento',
            field=models.CharField(choices=[('Identificación', 'Identificación Oficial'), ('Comprobante Domicilio', 'Comprobante de Domicilio'), ('Acta Nacimiento', 'Acta de Nacimiento'), ('Estudio Médico', 'Estudio Médico'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=25),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='fotografias',
            name='etapa',
            field=models.CharField(choices=[('Postulación', 'Postulación'), ('Seguimiento', 'Seguimiento'), ('Graduación', 'Graduación'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='geografia',
            name='codigo_postal',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos.', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Revisión', 'En Revisión'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientobeneficiario',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usoservicios',
            name='numero_acompanantes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='visita_postulante',
            name='estado_visita',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada')], default='Programada', max_length=50),
        ),
    ]
