# Generated by Django 6.0.1 on 2026-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0018_alter_apoyoeconomico_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentospersonales',
            name='tipo_documento',
            field=models.CharField(choices=[('Identificación', 'Identificación Oficial'), ('Comprobante Domicilio', 'Comprobante de Domicilio'), ('Acta Nacimiento', 'Acta de Nacimiento'), ('Estudio Médico', 'Estudio Médico')], default='Otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=25),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50),
        ),
    ]
